# Generated by Django 3.2.9 on 2021-12-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_is_active_transfer_is_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
