JWT_ALGORITHM = "HS256"
JWT_TOKEN_LIFETIME = 15
EMAIL_FIELD = "email"
USERNAME_FIELD = "username"
INITIAL_TEAM_MONEY = 5 * 1000 * 1000
INITIAL_PLAYER_COST = 1000 * 1000

GOALKEEPER = "Goalkeeper"
DEFENDER = "Defender"
MIDFIELDER = "Midfielder"
ATTACKER = "Attacker"

PLAYER_POSITIONS = (
    (GOALKEEPER, "Goalkeeper"),
    (DEFENDER, "Defender"),
    (MIDFIELDER, "Midfielder"),
    (ATTACKER, "Attacker"),
)

MINIMUM_AGE_FOR_PLAYER = 18
MAXIMUM_AGE_FOR_PLAYER = 40

DEFAULT_GOALKEEPER_AMOUNT = 3
DEFAULT_DEFENDER_AMOUNT = 6
DEFAULT_MIDFIELDER_AMOUNT = 6
DEFAULT_ATTACKER_AMOUNT = 5

PRICE_RAISE_DEPENDING_ON_POSITION = {
    ATTACKER: 1.3,
    MIDFIELDER: 1.2,
    DEFENDER: 1.1,
    GOALKEEPER: 1.1,
}

YOUNGEST_PLAYER_AGE = 21
YOUNG_PLAYER_AGE = 25

PRICE_RAISE_FOR_YOUNGEST_PLAYERS = 1.2
PRICE_RAISE_FOR_YOUNG_PLAYERS = 1.1

PRICE_RAISE_FOR_DOMESTIC_PLAYER = 1.2
